version: '3.8'

services:

  web:
    build: ./
    ports:
      - 8004:8000
    #command: uvicorn main:app --host 0.0.0.0 --reload
    command: sleep 9999h
    volumes:
      - ./:/usr/src/app
    environment:
      - JSONPLACEHOLDER_URL = ${JSONPLACEHOLDER_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./
    command: celery -A worker.celery_app worker --loglevel=info --logfile=./celery.log
    volumes:
      - ./:/usr/src/app
    environment:
      - JSONPLACEHOLDER_URL = ${JSONPLACEHOLDER_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7